name: healthque
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.12.1
  google_sign_in: ^6.3.0
  firebase_auth: ^5.5.1
  flutter_bloc: ^9.1.0
  freezed_annotation: ^3.0.0
  freezed: ^3.0.4
  intl_utils: ^2.8.10
  intl: ^0.19.0
  go_router: ^14.8.1
  google_nav_bar: ^5.0.7
  dio: ^5.8.0+1
  get_it: ^8.0.3
  gap: ^3.0.1
  syncfusion_flutter_sliders: ^28.2.12
  health: ^12.1.0
  permission_handler: ^11.4.0
  shared_preferences: ^2.5.2
  skeletonizer: ^1.4.3
  fl_chart: ^0.70.2
  flutter_localization: ^0.3.1
  flutter_localizations:
    sdk: flutter
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  json_serializable: ^6.9.4
  flutter_gen_runner: ^5.10.0

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_intl:
  enabled: true
  class_name: Strings
  main_locale: en
  arb_dir: lib/core/localization
  output_dir: lib/core/localization/generated

flutter_gen:
  output: lib/core/